### ISSUE TITLE
KeyError: 'tmdb_id'

### ISSUE THREAD

**Issue by the-archive** [KBlixt/PlexUnify#1]
When the script attempts o process a movie which isn't listed on tmdb it will fail with the error below:

```
Processing movie: "Top Gear the Great Adventures 3"
Traceback (most recent call last):
  File "PlexUnify.py", line 1143, in <module>
    main()
  File "PlexUnify.py", line 389, in main
    collection = get_collection_data()
  File "PlexUnify.py", line 281, in get_collection_data
    current_collection_metadata_holder = get_metadata_holder()
  File "PlexUnify.py", line 190, in get_metadata_holder
    get_tmdb_movie_metadata(movie)
  File "PlexUnify.py", line 1003, in get_tmdb_movie_metadata
    if movie['tmdb_id'] is None:
KeyError: 'tmdb_id'
```

Could the script be adapted to skip such movies rather than terminating?

**Comment by KBlixt** [comment]
Yes, I'll be fixing this tonight.

**Comment by KBlixt** [comment]
finally got time to do this. it should now be working. just make a git pull and all should be in order. if you still have issues, let me know. 

the reason behind the crash was that I guess that the movie in question isn't registered at either tmdb or imdb.
