### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Kussie** [KBlixt/PlexUnify#5]
Trying to run this at the moment on Ubuntu 18.04 and seeing the below error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 0: invalid continuation byte

```
Traceback (most recent call last):
  File "PlexUnify.py", line 36, in <module>
    config.read_file(open_config_file)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/codecs.py", line 713, in __next__
    return next(self.reader)
  File "/usr/lib/python3.6/codecs.py", line 644, in __next__
    line = self.readline()
  File "/usr/lib/python3.6/codecs.py", line 557, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python3.6/codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 0: invalid continuation byte
```

**Comment by Kussie** [comment]
Fixed by removing the UTF8 characters in the included config file.
